// Re-exported from @tinyclaw/heartware for backward compatibility
export {
  HeartwareManager,
  createHeartwareTools,
  loadHeartwareContext,
  loadMemoryByDate,
  loadMemoryRange,
  AuditLogger,
  computeContentHash,
  verifyContentHash,
  BackupManager,
  RateLimiter,
  validatePath,
  validateContent,
  validateFileSize,
  isAllowedFile,
  getAllowedFiles,
  getMemoryFilePattern,
  getTemplate,
  hasTemplate,
  getAllTemplates,
  HeartwareSecurityError,
  isHeartwareSecurityError,
  isSecurityErrorCode,
} from '@tinyclaw/heartware';

export type {
  HeartwareConfig,
  PathValidationResult,
  ContentValidationResult,
  ContentValidationRule,
  AuditLogEntry,
  BackupMetadata,
  RateLimitConfig,
  AllowedFile,
  SecurityErrorCode,
  SearchResult,
} from '@tinyclaw/heartware';
